### ISSUE TITLE
Anyone else getting issue:  Can't resolve 'fs' in '/node_modules/get-svg-colors' ?

### ISSUE THREAD

**Issue by makis-spy** [colorjs/get-image-colors#11]
This  library looks awesome but for the life of me cant get it going on storybook with webpack or nextjs.

**Comment by p-mcgowan** [comment]
I had the same issue, "fixed" by adding 
`node: { fs: 'empty' }` to `webpack.base.config`
eg:
```
module.exports = {
    entry: {
    ...
    module: { ... }
    node: { fs: 'empty' }
}
```
as per https://github.com/webpack-contrib/css-loader/issues/447

**Comment by zeke** [comment]
Sorry I missed this. Can one of you make a note of this in the README?

**Comment by TopzTheDev** [comment]
On your webpack config add this 

```
 build: {
    /*
     ** You can extend webpack config here
     */
    extend(config, ctx) {
      config.node = {
        fs: "empty"
      };
    }
  }
```

**Comment by zeke** [comment]
Thanks @TopzTheDev! Would you mind opening a PR to document this?
