### ISSUE TITLE
No Documentation of Options

### ISSUE THREAD

**Issue by anudeike** [colorjs/get-image-colors#19]
Hi Creators, 

This app is extremely helpful and works really well. But I am having trouble finding documentation on how I can specify the number of colors I want in my palette. 

Can you point me in the direction in the documentation if there is one? If there isn't can y'all write up one?

Thanks.

**Comment by ijambro** [comment]
I don't think there is a way for the caller of this module to specify the number of colors in the palette.  The value of 5 is hard-coded, and can only be changed in your local version under node_modules/get-image-colors/index.js.

I would also like to see this added as a new feature, so the caller of this module can specify this number as a parameter.  Would others agree?

Currently the "options" parameter is interpreted as either the callback function, or the file type that gets passed in to get-pixels.

**Comment by ijambro** [comment]
When I responded last month, I had overlooked the ability to pass an object as the "options" parameter.  It is actually easy to specify the number of colors you want in your palette.

I submitted a Pull Request to add this to the Readme:
https://github.com/colorjs/get-image-colors/pull/20

**Comment by zeke** [comment]
Sorry for the late reply. This was resolved by https://github.com/colorjs/get-image-colors/pull/20 which landed in 2.0.1
