### ISSUE TITLE
Update `get-svg-colors` to fix the `is-svg` dependency security issue

### ISSUE THREAD

**Issue by carloscuesta** [colorjs/get-image-colors#25]
Hello! 👋🏼 

This is related with https://github.com/colorjs/get-svg-colors/issues/72. The `is-svg` dependency used by `get-svg-colors` has a vulnerability, I already opened a PR to fix it https://github.com/colorjs/get-svg-colors/pull/73, as soon as we merge and release this we should update the dependency 😊

**Comment by adityapatadia** [comment]
@zeke can you release new version?

**Comment by zeke** [comment]
Hey color lovers!

Sorry I missed this and thanks for pinging me by name, @adityapatadia. I just published a new major version 2.0.0, in case there were any breaking changes since the last release (I didn't look too closely).

```
$ np 2.0.0 --no-2fa  

  ✔ Prerequisite check
  ✔ Git
  ✔ Cleanup
  ✔ Installing dependencies using npm
  ✔ Running tests using npm
  ✔ Bumping version using npm
  ✔ Publishing package using npm
  ✔ Pushing tags
  ✔ Creating release draft on GitHub

 get-svg-colors 2.0.0 published 🎉
```

**Comment by adityapatadia** [comment]
The problem is that current repo still installs `^1.5.1`. Can you update this repo as well to include 2.0.0?

**Comment by carloscuesta** [comment]
Created a PR to update the dependency in this repo as well: https://github.com/colorjs/get-image-colors/pull/28

**Comment by zeke** [comment]
Sorry I was a bit hasty and didn't notice which repo I was looking at, git-image-colors vs get-svg-colors. 🙈 

Just released a new version with the updated dep:

```
base $ np patch --no-2fa         

Commits:
- remove package lock  33fe744
- Update `get-svg-colors` dependency (#28)  26ad4bd

Commit Range:
v4.0.0...master

  ✔ Prerequisite check
  ✔ Git
  ✔ Cleanup
  ✔ Installing dependencies using npm
  ✔ Running tests using npm
  ✔ Bumping version using npm
  ✔ Publishing package using npm
  ✔ Pushing tags
  ✔ Creating release draft on GitHub

 get-image-colors 4.0.1 published 🎉
```
