### ISSUE TITLE
How can I get more than 5 colors from an image?

### ISSUE THREAD

**Issue by alanweissman** [colorjs/get-image-colors#8]
Would be very helpful thank you!

**Comment by zeke** [comment]
We'd need to update this line: https://github.com/zeke/get-image-colors/blob/master/index.js#L40

Simplest thing would be to just bump the value to something. I think I chose 5 because the accuracy diminishes quickly.

Care to submit a PR that changes this? If not, I can do it.

**Comment by zeke** [comment]
The number could be a parameter to the function, but that doesn't seem ideal to me.

I think we should just return more results and mention in the readme that mileage may vary.

**Comment by alanweissman** [comment]
Ok thanks sounds good I was able to bump that number to 15 and get good results. Optional first arg to function seems workable but just bumping higher is great. Appreciate the quick attention!

**Comment by kilianc** [comment]
I think having it as parameter with a decent default is the best. This way this can support all use cases!

**Comment by zeke** [comment]
Okay I'll do that and cut a new release in a bit.

**Comment by TheRyanHickman** [comment]
Following up on this? Curious if it was added

**Comment by zeke** [comment]
Gah. Sorry I dropped the ball on this. Might not get to it until next week, but if someone wants to open a PR with this change I can ship it quickly.

**Comment by clwheeler** [comment]
Looks like this is addressed here?
https://github.com/zeke/get-image-colors/pull/12

**Comment by dougmolineux** [comment]
+1 would love to see this feature, I can work on adding it @zeke if you don't want to merge in all of https://github.com/colorjs/get-image-colors/pull/12

**Comment by YouTwitFace** [comment]
@zeke #15

**Comment by zeke** [comment]
It's been a long time coming, but this https://github.com/colorjs/get-image-colors/pull/15 finally landed in a new release 2.0.0.

Thanks for your patience folks, and props to @YouTwitFace for the fix.
